version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "org.apache.santuario:xmlsec"
        update-types:
          - "version-update:semver-major"
  - package-ecosystem: "gomod"
    directory: "/ws024-relay"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
  - package-ecosystem: "pip"
    directory: "/tools"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
